### PR TITLE
SRE-144 Containerize Dewey

### PR DESCRIPTION
**Pull request by heschlie**
First go at running dewey in a containerized form. We still need to finish setting this up as a salt state, but I wanted to get some feedback before doing that work. There is a PR in dewey as well for generating the container.

### CODE REVIEW

**Comment by egh** [comment]
If we move towards containerizing apps, I wonder if we shouldn't simplify/drop these formulas and push the docker configuration into the app repo? With docker, all of these salt formulas begin to seem a little overly complicated. Running `docker compose up` (is that the right command?) in the dewey repo and getting the same thing we have in production on a developers machine would be great.

**Comment by heschlie** [comment]
Hey @egh while I agree with you in the grand scheme of things we still gain a lot out of salt using it as a sort of container orchestrator so we can handle things like secrets and varying configurations (while having them identical for each env would be ideal it is not where we are) from env to env, as well as managing the containers themselves to handle upgrading/downgrading/monitoring state. That isn't to say that there aren't methods of handling these things other than salt, but it is currently our most widely deployed tool for it, and make sense to keep using it.

In the longer term we would prefer to move to a proper orchestrator like k8s which would then manage all of those variables for us and we could more easily deploy an app the same way from dev up through to prod.

If you'd like to chat more about it (always enjoy dreaming of greener pastures) we should sit down and discuss more!

**Comment by egh** [comment]
I hear you, I see that salt should be our configuration system at least in the near term. I guess I worry about code duplication if salt is managing `docker-compose.yml` files, though. I feel like those could be closer to the core dewey repository, so that devs could bring up a containerized version of dewey in a local environment without needing to go to the formula to find it. Maybe this isn't worth the effort, though. I'm not sure what our docker strategy looks like.

**Comment by heschlie** [comment]
@egh actually that is the end goal of this, to be able to bringup dewey by simply doing a `docker-compose up` on the compose file, I was torn on where to host it though. I did originally have it in the dewey repo, but it feels more appropriate here in my opinion as salt needs to be able to access it. I should however put a note in the dewey repo to point users to this to bringup the application.

If we were to host the compose file in the dewey repo we'd have to pull it into the formula or duplicate it in both places. Since the dockerfile has no hard requirement on where it should be hosted it made setting up the formula a bit easier.

**Comment by egh** [comment]
@heschlie My concern here is setting a pattern that I think is going to be awkward for devs and for testing. Setting aside dewey, I'm concerned that developers may not even *know* there is a docker compose file available. And if they do, it does add an additional step of downloading it. Or, if we want to set up integration testing, we might want to use docker compose to bring up an instance, and it would be awkward to have to get it from the salt formula. But maybe we can set up a curl command to download the docker-compose.yml

**Comment by sgatchell** [comment]
Conversely, if the docker-compose file resides in the app repo instead of the formula then the burden is on the salt state to pull the compose file.  I would prefer this, as then the burden is on an automated process rather than a manual process.  

I'm also open to keeping files in both the repo and the formula. It's possible that the setup will be different enough between local docker and docker-in-vm that we'd feel more pain from trying to maintain a file that handles both environments.

**Pull request closed without merging**
